# -*- coding: utf-8 -*-
"""Text_Summarization_using_BART_Transformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ukaI_vAlEUeCT6ZgGd-04AI-GzZGDgYs
"""

!pip install datasets

# Loading the dataset
from datasets import load_dataset

ds = load_dataset("knkarthick/dialogsum")

ds

ds['train'][1]['dialogue']

ds['train'][1]['summary']

"""# WITHOUT FINE-TUNING"""

!pip install transformers

from transformers import pipeline

pipe = pipeline("summarization", model="facebook/bart-large-cnn")

article_1 = ds['train'][1]['dialogue']

pipe(article_1, max_length = 20, min_length = 10, do_sample = False)

"""# WITH FINE-TUNING"""

# Load model directly
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("facebook/bart-large-cnn")
model = AutoModelForSeq2SeqLM.from_pretrained("facebook/bart-large-cnn")

# tokenization
def preprocessor_function(batch):
  source = batch['dialogue']
  target = batch['summary']
  source_ids = tokenizer(source, truncation = True, padding = 'max_length', max_length = 128)
  target_ids = tokenizer(target, truncation = True, padding = 'max_length', max_length = 128)

  labels = target_ids['input_ids']
  labels = [[(label if label != tokenizer.pad_token_id else - 100) for label in labels_example] for labels_example in labels]

  return {
      "input_ids": source_ids["input_ids"],
      "attention_mask": source_ids["attention_mask"],
      "labels": labels
  }

df_source = ds.map(preprocessor_function, batched = True)

import os
os.environ['WANDB_DISABLED'] = 'True'

# training_arguments
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir = "/content",
    per_device_train_batch_size = 8,
    num_train_epochs = 2,
    remove_unused_columns = True
)

trainer = Trainer(
    model = model,
    args = training_args,
    train_dataset = df_source['train'],
    eval_dataset = df_source['test']
)

trainer.train()

eval_results = trainer.evaluate()

eval_results

"""# Saving the model"""

model.save_pretrained("/content/model_directory")
tokenizer.save_pretrained("/content/model_directory")

tokenizer = AutoTokenizer.from_pretrained("/content/model_directory")
model = AutoModelForSeq2SeqLM.from_pretrained("/content/model_directory")

def summarize(blog_post):
    # Tokenize the input blog post
    inputs = tokenizer(blog_post, max_length=1024, truncation=True, return_tensors='pt')

    # Debug: Print token count
    print(f"Input token count: {len(inputs['input_ids'][0])}")

    # Generate the summary
    summary_ids = model.generate(inputs['input_ids'], max_length=150, min_length=40, length_penalty=2.0, num_beams=4, early_stopping=True)

    # Debug: Print generated token count
    print(f"Generated token count: {len(summary_ids[0])}")

    # decode the summary
    summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

    # Debug: Print raw summary with special tokens
    raw_summary = tokenizer.decode(summary_ids[0], skip_special_tokens=False)
    print(f"Raw summary (with special tokens): {raw_summary}")

    return summary

blog_post = """
# The Future of Remote Work: Balancing Flexibility and Collaboration

The COVID-19 pandemic forced an unprecedented shift to remote work, transforming what was once considered a privilege into a necessity overnight. As we move beyond the immediate crisis, organizations worldwide are reimagining the future of work. This evolution isn't simply about deciding between in-office or remote work—it's about creating sustainable models that balance employee flexibility with organizational needs.

## Remote Work: The New Normal

Recent studies suggest that approximately 25% of all professional jobs in North America will be remote by the end of 2022, with that number continuing to grow through 2023. This shift represents more than a temporary adjustment; it signals a fundamental change in how we conceptualize work.

The benefits for employees are well-documented: eliminated commutes, improved work-life balance, and the ability to work from anywhere. Companies have discovered their own advantages, from reduced office costs to access to global talent pools previously limited by geography. Productivity, contrary to early fears, has generally increased, though with important nuances across different roles and industries.

## Challenges in the Distributed Workforce

Despite these benefits, fully remote environments present significant challenges. Zoom fatigue—that unique exhaustion that comes from video conferencing—has become a recognized phenomenon. Many workers report difficulty in maintaining boundaries between work and personal life, with workdays often extending beyond traditional hours.

Perhaps most concerning is the impact on organizational culture and spontaneous collaboration. The casual conversations by the coffee machine, impromptu brainstorming sessions, and organic mentoring that occur in physical workspaces are difficult to replicate virtually. New employees particularly struggle to absorb company culture and build relationships in fully remote settings.

## Hybrid Models: The Emerging Compromise

In response, many organizations are adopting hybrid work models that combine remote flexibility with in-person collaboration. These approaches vary widely:

1. **Designated in-office days**: Teams coordinate to be present on specific days, maximizing collaborative opportunities.
2. **Activity-based planning**: Work location decisions based on the nature of tasks, with collaborative activities scheduled for office days.
3. **Hub-and-spoke models**: Organizations maintain smaller satellite offices closer to where employees live, reducing commutes while preserving in-person options.

Google's approach exemplifies this hybrid evolution. Their "flexible workweek" asks employees to be in the office three days per week, with teams deciding which days work best for their collaborative needs. They've also redesigned office spaces to support team collaboration rather than individual work.

## Technology Enabling the Transition

Technology companies are racing to fill the gaps in the remote work experience. Virtual reality meeting spaces, digital whiteboards, and asynchronous collaboration tools are evolving rapidly. These innovations aim to overcome the limitations of current videoconferencing platforms that inadequately replicate in-person interactions.

Microsoft's Mesh platform, for example, allows people in different physical locations to join collaborative experiences with the presence of being together. Similarly, startups like Teamflow are creating virtual offices where employees can "see" colleagues and spontaneously connect, mimicking the casual interactions of physical spaces.

## The Path Forward: Intentional Design

As we navigate this transformation, the most successful organizations will be those that approach remote and hybrid work with intentionality. Rather than simply replicating office-based processes online, they will reimagine workflows, communication patterns, and collaboration methods for distributed teams.

The future of work requires balancing the autonomy employees have grown accustomed to with the collaborative culture that drives innovation. Organizations that can strike this balance—providing flexibility while fostering meaningful connection—will create sustainable models that attract and retain top talent in the evolving workplace landscape.

The coming years will likely see continued experimentation as organizations learn what works best for their unique contexts. What's clear is that there's no returning to the pre-pandemic status quo—the future of work has been fundamentally altered, and those who adapt thoughtfully will thrive in this new reality.
"""

summary = summarize(blog_post)
print(f'Summary: {summary}')

dialogue_example = """
User: I need to reschedule my appointment for next week.
Agent: I'd be happy to help you with that. May I have your name and the current appointment date?
User: My name is Alex Smith and my appointment is for Monday at 2pm.
Agent: Thank you, Mr. Smith. I see your appointment here. What day and time would work better for you next week?
User: Would Thursday at 10am be available?
Agent: Let me check... Yes, Thursday at 10am is available. Would you like me to reschedule your appointment for that time?
User: Yes, please. And can you send me a confirmation email?
Agent: Absolutely. I've rescheduled your appointment for Thursday at 10am, and I'll send a confirmation email to the address we have on file. Is there anything else I can help you with today?
User: No, that's all. Thank you for your help.
Agent: You're welcome, Mr. Smith. We look forward to seeing you next Thursday at 10am. Have a great day!
"""

summary = summarize(dialogue_example)
print(f'Summary: {summary}')

